# Generated by Django 4.0.4 on 2022-11-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0002_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecg_data',
            name='created_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ecg_data',
            name='ecg_user',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='ecg_data',
            name='ecg',
            field=models.TextField(),
        ),
    ]
