# Generated by Django 4.0.4 on 2022-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0005_remove_ecg_data_additional_data_ecg_data_micro_dust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecg_data',
            name='micro_dust',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ecg_data',
            name='temperature',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ecg_data',
            name='tmicro_dust',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ecg_data',
            name='uv_ray',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ecg_data',
            name='weather',
            field=models.CharField(max_length=15),
        ),
    ]
